schemaVersion: '2.0.0'
commandTests:
  - name: "terraform installation"
    command: "which"
    args: ["terraform"]
    expectedOutput: ["/usr/bin/terraform\n"]

  - name: "terraform version"
    command: "terraform"
    args: ["version"]
    expectedOutput: ["v0.11.3\n"]

  - name: "awless installation"
    command: "which"
    args: ["awless"]
    expectedOutput: ["/usr/bin/awless\n"]

  - name: "awless version"
    command: "awless"
    args: ["version"]
    expectedOutput: ["v0.1.10"]
