schemaVersion: '2.0.0'
commandTests:
  - name: "terraform installation"
    command: "which"
    args: ["terraform"]
    expectedOutput: ["/usr/bin/terraform\n"]

  - name: "terraform version"
    command: "terraform"
    args: ["version"]
    expectedOutput: ["v0.11.10\n"]

  - name: "awless installation"
    command: "which"
    args: ["awless"]
    expectedOutput: ["/usr/bin/awless\n"]

  - name: "awless version"
    command: "awless"
    args: ["version"]
    expectedOutput: ["v0.1.11"]

  - name: "packer version"
    command: "packer"
    args: ["--version"]
    expectedOutput: [
        "1.1.3\n",
        ]

  - name: "make version"
    command: "make"
    args: ["-v"]
    expectedOutput: ["GNU Make 4.2.*"]

  - name: "jq installation"
    command: "jq"
    args: ["--version"]
    expectedOutput: ["jq-1.6"]
