schemaVersion: '2.0.0'
commandTests:
  - name: "terraform installation"
    command: "terraform"
    args: ["version"]
    expectedOutput: ["v0.11.12\n"]

  - name: "awless installation"
    command: "awless"
    args: ["version"]
    expectedOutput: ["v0.1.11"]

  - name: "packer installation"
    command: "packer"
    args: ["--version"]
    expectedOutput: [
        "1.1.3\n",
        ]

  - name: "make installation"
    command: "make"
    args: ["-v"]
    expectedOutput: ["GNU Make 4.2.*"]

  - name: "jq installation"
    command: "jq"
    args: ["--version"]
    expectedOutput: ["jq-1.6"]

  - name: "ssh-keyscan installation"
    command: "which"
    args: ["ssh-keyscan"]
    expectedOutput: ["/usr/bin/ssh-keyscan"]

  - name: "ssh installation"
    command: "which"
    args: ["ssh"]
    expectedOutput: ["/usr/bin/ssh"]

  - name: "bash installation"
    command: "bash"
    args: ["--version"]
    expectedOutput: ["GNU bash, version 5.0.0.*"]
